import { ArtStyle } from '@/types';

export const artStyles: ArtStyle[] = [
  // Classic Fine Art
  {
    id: 'impressionism',
    name: 'Impressionism',
    category: 'classic',
    description: 'Soft brushstrokes, light and color',
    promptPrefix: 'Impressionist painting style, soft brushstrokes, vibrant light and color, reminiscent of Monet',
  },
  {
    id: 'post-impressionism',
    name: 'Post-Impressionism',
    category: 'classic',
    description: 'Bold colors, expressive forms',
    promptPrefix: 'Post-Impressionist painting style, bold expressive colors, distinctive brushwork like Van Gogh',
  },
  {
    id: 'baroque',
    name: 'Baroque',
    category: 'classic',
    description: 'Dramatic, rich, ornate',
    promptPrefix: 'Baroque painting style, dramatic lighting, rich colors, ornate details, chiaroscuro',
  },
  {
    id: 'renaissance',
    name: 'Renaissance',
    category: 'classic',
    description: 'Classical beauty, perspective',
    promptPrefix: 'Renaissance painting style, classical beauty, perfect perspective, harmonious composition',
  },
  {
    id: 'art-nouveau',
    name: 'Art Nouveau',
    category: 'classic',
    description: 'Organic lines, decorative',
    promptPrefix: 'Art Nouveau style, flowing organic lines, decorative patterns, elegant curves like Mucha',
  },
  {
    id: 'art-deco',
    name: 'Art Deco',
    category: 'classic',
    description: 'Geometric, glamorous, bold',
    promptPrefix: 'Art Deco style, geometric patterns, bold symmetry, glamorous luxury, gold accents',
  },
  {
    id: 'surrealism',
    name: 'Surrealism',
    category: 'classic',
    description: 'Dreamlike, fantastical',
    promptPrefix: 'Surrealist painting style, dreamlike imagery, fantastical elements like Salvador Dali',
  },
  {
    id: 'romanticism',
    name: 'Romanticism',
    category: 'classic',
    description: 'Emotional, sublime nature',
    promptPrefix: 'Romantic era painting style, emotional intensity, sublime landscapes, dramatic atmosphere',
  },
  {
    id: 'pre-raphaelite',
    name: 'Pre-Raphaelite',
    category: 'classic',
    description: 'Vivid colors, intricate detail',
    promptPrefix: 'Pre-Raphaelite painting style, vivid colors, intricate details, medieval romanticism',
  },
  {
    id: 'ukiyo-e',
    name: 'Ukiyo-e',
    category: 'classic',
    description: 'Japanese woodblock prints',
    promptPrefix: 'Ukiyo-e Japanese woodblock print style, flat colors, bold outlines like Hokusai',
  },
  {
    id: 'pointillism',
    name: 'Pointillism',
    category: 'classic',
    description: 'Dots of pure color',
    promptPrefix: 'Pointillist painting style, composed of small dots of pure color like Seurat',
  },
  {
    id: 'fauvism',
    name: 'Fauvism',
    category: 'classic',
    description: 'Wild, vibrant colors',
    promptPrefix: 'Fauvist painting style, wild vibrant colors, bold brushwork like Matisse',
  },
  {
    id: 'realism',
    name: 'Realism',
    category: 'classic',
    description: 'Precise, lifelike depiction',
    promptPrefix: 'Realist painting style, precise lifelike depiction, meticulous attention to detail, Gustave Courbet inspired, everyday subjects rendered with photographic accuracy, natural lighting',
  },
  {
    id: 'rococo',
    name: 'Rococo',
    category: 'classic',
    description: 'Ornate, pastel, playful',
    promptPrefix: 'Rococo painting style, ornate decorative flourishes, soft pastel colors, playful romantic scenes, Fragonard and Boucher inspired, gilded elegance, cherubs and flowers',
  },
  {
    id: 'neoclassicism',
    name: 'Neoclassicism',
    category: 'classic',
    description: 'Greek and Roman grandeur',
    promptPrefix: 'Neoclassical painting style, Greek and Roman inspired grandeur, noble subjects, Jacques-Louis David aesthetic, heroic compositions, marble-like skin tones, dignified poses',
  },
  {
    id: 'expressionism',
    name: 'Expressionism',
    category: 'classic',
    description: 'Emotional, distorted forms',
    promptPrefix: 'Expressionist painting style, raw emotional intensity, distorted forms and perspectives, Edvard Munch and Egon Schiele inspired, psychological depth, bold angular brushwork',
  },
  {
    id: 'cubism',
    name: 'Cubism',
    category: 'classic',
    description: 'Geometric fragmentation',
    promptPrefix: 'Cubist painting style, geometric fragmentation, multiple perspectives simultaneously, Picasso and Braque inspired, fractured planes, muted earth tones with color accents',
  },
  {
    id: 'dutch-golden-age',
    name: 'Dutch Golden Age',
    category: 'classic',
    description: 'Vermeer interiors, rich detail',
    promptPrefix: 'Dutch Golden Age painting style, Vermeer and Rembrandt inspired, rich chiaroscuro lighting, intimate domestic scenes, exquisite fabric textures, luminous pearl-like highlights',
  },
  {
    id: 'ink-wash',
    name: 'Chinese Ink Wash',
    category: 'classic',
    description: 'Traditional Asian brushwork',
    promptPrefix: 'Traditional Chinese ink wash painting, Shan shui landscape style, masterful brushwork, misty mountains, flowing water, minimalist composition, Zen-like tranquility, rice paper texture',
  },
  {
    id: 'symbolism',
    name: 'Symbolism',
    category: 'classic',
    description: 'Mystical, allegorical imagery',
    promptPrefix: 'Symbolist painting style, mystical and allegorical imagery, Gustave Moreau and Odilon Redon inspired, dreamlike atmosphere, hidden meanings, jewel-like colors, ethereal figures',
  },
  {
    id: 'hudson-river',
    name: 'Hudson River School',
    category: 'classic',
    description: 'American romantic landscapes',
    promptPrefix: 'Hudson River School painting style, American romantic landscape, Thomas Cole and Albert Bierstadt inspired, majestic wilderness, golden atmospheric light, sublime nature, panoramic vistas',
  },
  {
    id: 'tonalism',
    name: 'Tonalism',
    category: 'classic',
    description: 'Atmospheric, muted tones',
    promptPrefix: 'Tonalist painting style, atmospheric muted tones, James McNeill Whistler inspired, soft diffused light, poetic mood, limited palette, nocturnal scenes, meditative quality',
  },
  {
    id: 'academic',
    name: 'Academic Art',
    category: 'classic',
    description: 'Formal classical technique',
    promptPrefix: 'Academic painting style, formal classical technique, William-Adolphe Bouguereau inspired, flawless rendering, idealized beauty, mythological or historical subjects, polished finish',
  },
  {
    id: 'luminism',
    name: 'Luminism',
    category: 'classic',
    description: 'Radiant light, serene landscapes',
    promptPrefix: 'Luminist painting style, radiant glowing light, Fitz Henry Lane inspired, serene coastal landscapes, mirror-like water reflections, hidden brushwork, transcendent atmosphere',
  },

  // Modern & Digital
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    category: 'modern',
    description: 'Neon, futuristic, dystopian',
    promptPrefix: 'Cyberpunk art style, neon lights, futuristic dystopian, high tech low life aesthetic',
  },
  {
    id: 'vaporwave',
    name: 'Vaporwave',
    category: 'modern',
    description: 'Retro-futuristic, nostalgic',
    promptPrefix: 'Vaporwave aesthetic, pink and cyan colors, retro-futuristic, 80s nostalgia, glitch elements',
  },
  {
    id: 'synthwave',
    name: 'Synthwave',
    category: 'modern',
    description: 'Retro 80s, neon grids',
    promptPrefix: 'Synthwave retro style, neon pink and purple, 80s grid landscapes, chrome reflections',
  },
  {
    id: 'minimalist',
    name: 'Minimalist',
    category: 'modern',
    description: 'Clean, simple, elegant',
    promptPrefix: 'Minimalist art style, clean lines, simple shapes, elegant negative space, refined',
  },
  {
    id: 'abstract-expressionism',
    name: 'Abstract Expressionism',
    category: 'modern',
    description: 'Bold, emotional abstraction',
    promptPrefix: 'Abstract Expressionist painting, bold gestural brushstrokes, emotional intensity',
  },
  {
    id: 'pop-art',
    name: 'Pop Art',
    category: 'modern',
    description: 'Bold colors, commercial art',
    promptPrefix: 'Pop Art style, bold primary colors, Ben-Day dots, commercial aesthetic like Warhol',
  },
  {
    id: 'bauhaus',
    name: 'Bauhaus',
    category: 'modern',
    description: 'Functional, geometric shapes',
    promptPrefix: 'Bauhaus design style, primary colors, geometric shapes, functional modernism',
  },
  {
    id: 'geometric',
    name: 'Geometric Abstract',
    category: 'modern',
    description: 'Pure shapes and forms',
    promptPrefix: 'Geometric abstract art, pure shapes, mathematical precision, bold color blocks',
  },
  {
    id: 'glitch-art',
    name: 'Glitch Art',
    category: 'modern',
    description: 'Digital corruption aesthetic',
    promptPrefix: 'Glitch art style, digital corruption, pixel sorting, chromatic aberration, databending',
  },
  {
    id: 'low-poly',
    name: 'Low Poly',
    category: 'modern',
    description: 'Triangular faceted surfaces',
    promptPrefix: 'Low poly 3D art style, triangular facets, crystalline surfaces, modern digital',
  },
  {
    id: 'pixel-art',
    name: 'Pixel Art',
    category: 'modern',
    description: 'Retro game aesthetic',
    promptPrefix: 'Pixel art style, 16-bit aesthetic, retro gaming, limited color palette',
  },
  {
    id: 'neon-noir',
    name: 'Neon Noir',
    category: 'modern',
    description: 'Dark, moody, neon accents',
    promptPrefix: 'Neon noir style, dark moody atmosphere, neon light accents, cinematic shadows',
  },
  {
    id: 'retrowave',
    name: 'Retrowave',
    category: 'modern',
    description: '80s sunset gradients',
    promptPrefix: 'Retrowave aesthetic, warm sunset gradients of orange pink and purple, silhouetted palm trees, vintage sports car, chrome reflections, VHS scan lines, nostalgic 1980s Miami vibes',
  },
  {
    id: 'outrun',
    name: 'Outrun',
    category: 'modern',
    description: 'Fast cars, neon grids',
    promptPrefix: 'Outrun aesthetic, high speed Ferrari Testarossa, infinite neon grid horizon, setting sun, chrome and glass reflections, speed lines, synthwave album cover style',
  },
  {
    id: 'brutalist',
    name: 'Brutalist',
    category: 'modern',
    description: 'Raw concrete, stark forms',
    promptPrefix: 'Brutalist architecture aesthetic, raw exposed concrete, monumental geometric forms, stark shadows, Le Corbusier inspired, imposing scale, Soviet-era monumentalism',
  },
  {
    id: 'memphis',
    name: 'Memphis Design',
    category: 'modern',
    description: '80s patterns, bold shapes',
    promptPrefix: 'Memphis Design style, bold geometric patterns, squiggles and terrazzo, bright clashing colors, Ettore Sottsass inspired, playful postmodern aesthetic, 1980s Italian design',
  },
  {
    id: 'isometric',
    name: 'Isometric',
    category: 'modern',
    description: '3D orthographic view',
    promptPrefix: 'Isometric 3D illustration style, precise 30-degree angles, detailed miniature world, vibrant flat colors, video game aesthetic, clean vector edges, diorama-like presentation',
  },
  {
    id: 'flat-design',
    name: 'Flat Design',
    category: 'modern',
    description: 'Simple, clean 2D',
    promptPrefix: 'Modern flat design illustration, simple geometric shapes, bold solid colors, no gradients or shadows, minimalist UI aesthetic, clean vector art, contemporary digital style',
  },
  {
    id: 'gradient-mesh',
    name: 'Gradient Mesh',
    category: 'modern',
    description: 'Smooth flowing colors',
    promptPrefix: 'Gradient mesh art style, smooth flowing color transitions, abstract organic forms, vibrant aurora-like blends, silk-like texture, Apple Music style visuals, liquid color movements',
  },
  {
    id: 'duotone',
    name: 'Duotone',
    category: 'modern',
    description: 'Two-color palette',
    promptPrefix: 'Duotone design style, dramatic two-color palette, high contrast, Spotify style aesthetic, bold graphic impact, modern editorial look, striking color combination',
  },
  {
    id: 'holographic',
    name: 'Holographic',
    category: 'modern',
    description: 'Iridescent rainbow chrome',
    promptPrefix: 'Holographic aesthetic, iridescent rainbow chrome surfaces, oil-slick color shifts, futuristic materials, Y2K revival style, prismatic light reflections, metallic shimmer',
  },
  {
    id: 'y2k',
    name: 'Y2K Aesthetic',
    category: 'modern',
    description: 'Early 2000s futurism',
    promptPrefix: 'Y2K aesthetic, early 2000s digital futurism, chrome bubbles, translucent plastics, tech-optimism, inflatable furniture vibes, silver and baby blue, millennium nostalgia',
  },
  {
    id: 'solarpunk',
    name: 'Solarpunk',
    category: 'modern',
    description: 'Green utopian futurism',
    promptPrefix: 'Solarpunk aesthetic, optimistic green futurism, sustainable technology, vertical gardens, solar panels integrated with nature, art nouveau meets eco-tech, hopeful tomorrow',
  },
  {
    id: 'dark-academia',
    name: 'Dark Academia',
    category: 'modern',
    description: 'Scholarly gothic romance',
    promptPrefix: 'Dark Academia aesthetic, vintage library atmosphere, warm candlelight on leather-bound books, gothic architecture, autumn leaves, scholarly romance, sepia and burgundy tones',
  },

  // Modern Fine Art Styles
  {
    id: 'color-field',
    name: 'Color Field',
    category: 'fine-art',
    description: 'Large planes of color, Rothko-inspired',
    promptPrefix: 'Color Field painting in the style of Mark Rothko, luminous rectangular color planes with soft edges, transcendent and meditative, subtle color gradations, spiritual depth through pure color relationships, museum-quality fine art',
  },
  {
    id: 'hard-edge',
    name: 'Hard Edge',
    category: 'fine-art',
    description: 'Sharp geometric boundaries',
    promptPrefix: 'Hard Edge painting style, crisp precise geometric shapes with razor-sharp boundaries, flat unmodulated color areas, bold color contrasts, Ellsworth Kelly and Frank Stella inspired, pristine execution',
  },
  {
    id: 'lyrical-abstraction',
    name: 'Lyrical Abstraction',
    category: 'fine-art',
    description: 'Flowing, expressive forms',
    promptPrefix: 'Lyrical Abstraction painting, flowing organic forms, expressive gestural marks, luminous washes of color, poetic and emotional, Helen Frankenthaler soak-stain technique, ethereal and graceful',
  },
  {
    id: 'neo-expressionism',
    name: 'Neo-Expressionism',
    category: 'fine-art',
    description: 'Raw, intense, Basquiat-style',
    promptPrefix: 'Neo-Expressionist painting, raw emotional intensity, bold primitive marks, graffiti influences, Basquiat and Schnabel inspired, visceral energy, thick impasto textures, symbolic imagery, urban edge',
  },
  {
    id: 'contemporary-realism',
    name: 'Contemporary Realism',
    category: 'fine-art',
    description: 'Photorealistic modern subjects',
    promptPrefix: 'Contemporary Realism painting, photorealistic precision with modern sensibility, hyperreal details, dramatic contemporary lighting, Chuck Close and Richard Estes inspired, technically masterful execution',
  },
  {
    id: 'digital-fine-art',
    name: 'Digital Fine Art',
    category: 'fine-art',
    description: 'High-end digital painting',
    promptPrefix: 'Museum-quality digital fine art, sophisticated digital painting techniques, rich layered textures, contemporary digital masters style, exhibition-worthy digital artwork, refined and polished',
  },
  {
    id: 'mixed-media',
    name: 'Mixed Media',
    category: 'fine-art',
    description: 'Layered textures, collage',
    promptPrefix: 'Mixed media fine art, layered collage textures, torn paper edges, paint drips over photographs, Robert Rauschenberg combines style, rich tactile surfaces, found object aesthetic',
  },
  {
    id: 'conceptual-minimal',
    name: 'Conceptual Minimal',
    category: 'fine-art',
    description: 'Idea-driven, spare aesthetic',
    promptPrefix: 'Conceptual Minimalist art, spare and intentional, Donald Judd and Sol LeWitt inspired, pure form and idea, industrial materials aesthetic, gallery white space, intellectual rigor',
  },
  {
    id: 'new-media',
    name: 'New Media Art',
    category: 'fine-art',
    description: 'Technology-inspired aesthetics',
    promptPrefix: 'New Media digital art, technology-inspired contemporary aesthetics, data visualization beauty, generative art patterns, TeamLab and Refik Anadol inspired, immersive digital experience',
  },
  {
    id: 'process-art',
    name: 'Process Art',
    category: 'fine-art',
    description: 'Evidence of creation visible',
    promptPrefix: 'Process Art style, visible evidence of artistic creation, drips and splatters, Pollock action painting energy, spontaneous mark-making, raw creative process captured, authentic and unpolished',
  },
  {
    id: 'arte-povera',
    name: 'Arte Povera',
    category: 'fine-art',
    description: 'Raw, humble materials',
    promptPrefix: 'Arte Povera style, raw humble materials transformed into art, burlap canvas and rusted metal, Jannis Kounellis inspired, anti-commercial aesthetic, natural elements, gallery installation feel',
  },
  {
    id: 'suprematism',
    name: 'Suprematism',
    category: 'fine-art',
    description: 'Malevich geometric purity',
    promptPrefix: 'Suprematist painting style, Kazimir Malevich inspired, pure geometric abstraction, floating squares circles and lines, limited color palette, white void space, spiritual geometry',
  },
  {
    id: 'de-stijl',
    name: 'De Stijl',
    category: 'fine-art',
    description: 'Mondrian primary colors',
    promptPrefix: 'De Stijl style, Piet Mondrian inspired, strict primary colors red yellow blue, black grid lines on white, perfect right angles, neoplasticism, harmonious geometric balance',
  },
  {
    id: 'op-art',
    name: 'Op Art',
    category: 'fine-art',
    description: 'Optical illusions, movement',
    promptPrefix: 'Op Art style, optical illusion patterns, Bridget Riley and Victor Vasarely inspired, black and white geometric patterns, vibrating visual effects, dizzying movement, retinal stimulation',
  },
  {
    id: 'kinetic-art',
    name: 'Kinetic Art',
    category: 'fine-art',
    description: 'Movement and patterns',
    promptPrefix: 'Kinetic art style, dynamic movement implied through pattern, Alexander Calder mobile aesthetic, rhythmic repetition, suspended elements, motion blur effect, sculptural energy',
  },
  {
    id: 'abstract-landscape',
    name: 'Abstract Landscape',
    category: 'fine-art',
    description: 'Nature through abstraction',
    promptPrefix: 'Abstract landscape painting, Richard Diebenkorn Ocean Park series inspired, abstracted natural forms, horizon lines and color fields, gestural marks suggesting terrain, contemplative atmosphere',
  },
  {
    id: 'photorealism',
    name: 'Photorealism',
    category: 'fine-art',
    description: 'Hyperrealistic painting',
    promptPrefix: 'Photorealist painting style, hyperrealistic detail from photographic source, Chuck Close and Richard Estes inspired, every reflection captured, trompe loeil precision, indistinguishable from photograph',
  },
  {
    id: 'street-art',
    name: 'Street Art',
    category: 'fine-art',
    description: 'Urban murals, Banksy influence',
    promptPrefix: 'Contemporary street art style, bold urban mural aesthetic, stencil techniques, Banksy and Shepard Fairey influenced, social commentary, wheat paste texture, city wall canvas',
  },
  {
    id: 'biomorphic',
    name: 'Biomorphic Abstraction',
    category: 'fine-art',
    description: 'Organic abstract forms',
    promptPrefix: 'Biomorphic abstraction style, organic flowing forms, Joan Miro and Jean Arp inspired, amoeba-like shapes, natural curves, playful yet sophisticated, living geometry',
  },
  {
    id: 'monochrome',
    name: 'Monochrome',
    category: 'fine-art',
    description: 'Single color exploration',
    promptPrefix: 'Monochrome painting style, Yves Klein and Ad Reinhardt inspired, single color in infinite variations, texture through brushwork, meditative depth, subtle tonal shifts within one hue',
  },
  {
    id: 'tachisme',
    name: 'Tachisme',
    category: 'fine-art',
    description: 'European abstract expressionism',
    promptPrefix: 'Tachisme painting style, European lyrical abstraction, spontaneous brushwork and stains, Georges Mathieu inspired, calligraphic energy, emotional immediacy, art informel aesthetic',
  },
  {
    id: 'assemblage',
    name: 'Assemblage',
    category: 'fine-art',
    description: 'Found object sculpture',
    promptPrefix: 'Assemblage art style, found object composition, Joseph Cornell box aesthetic, vintage ephemera collaged with meaning, shadow box presentation, poetic juxtaposition of objects',
  },

  // Photography Styles
  {
    id: 'cinematic',
    name: 'Cinematic',
    category: 'photography',
    description: 'Movie-like, dramatic',
    promptPrefix: 'Award-winning cinematic photography, ARRI Alexa camera aesthetic, anamorphic lens flares, film grain texture, Hollywood color grading with teal shadows and orange highlights, dramatic volumetric lighting with god rays, shallow depth of field f/1.4, professional movie still quality, Roger Deakins inspired cinematography',
  },
  {
    id: 'film-noir',
    name: 'Film Noir',
    category: 'photography',
    description: 'High contrast, shadows',
    promptPrefix: 'Classic film noir photography, stark black and white with deep shadows, venetian blind light patterns, cigarette smoke wisps, wet rain-slicked streets reflecting neon, high contrast chiaroscuro lighting, 1940s detective movie aesthetic, moody and mysterious atmosphere',
  },
  {
    id: 'golden-hour',
    name: 'Golden Hour',
    category: 'photography',
    description: 'Warm sunset lighting',
    promptPrefix: 'Breathtaking golden hour photography, warm amber and honey tones, long dramatic shadows, sun flare and lens bloom, backlit subjects with rim lighting, soft diffused sunlight, magical warm atmosphere, professional landscape photography, 85mm lens portrait quality',
  },
  {
    id: 'blue-hour',
    name: 'Blue Hour',
    category: 'photography',
    description: 'Cool twilight tones',
    promptPrefix: 'Ethereal blue hour photography, deep cobalt and indigo twilight sky, city lights beginning to glow, long exposure smoothness, reflections on water, serene melancholic mood, professional twilight landscape, cool color temperature 4000K',
  },
  {
    id: 'macro',
    name: 'Macro Photography',
    category: 'photography',
    description: 'Extreme close-up detail',
    promptPrefix: 'Stunning macro photography, extreme close-up revealing hidden worlds, razor-thin depth of field, intricate textures and patterns, professional focus stacking sharpness, vibrant colors, nature documentary quality, 100mm macro lens',
  },
  {
    id: 'aerial',
    name: 'Aerial View',
    category: 'photography',
    description: 'Bird\'s eye perspective',
    promptPrefix: 'Dramatic aerial photography, stunning birds eye perspective revealing patterns and scale, abstract geometric compositions from above, professional drone cinematography, rich saturated colors, epic sense of scale, National Geographic quality',
  },
  {
    id: 'portrait',
    name: 'Portrait',
    category: 'photography',
    description: 'Elegant portrait lighting',
    promptPrefix: 'Museum-quality portrait photography, Rembrandt lighting with perfect catchlights, creamy bokeh background f/1.2, skin texture visible but flattering, 85mm lens compression, studio quality three-point lighting, emotional depth in eyes, Annie Leibovitz inspired portraiture',
  },
  {
    id: 'landscape',
    name: 'Landscape',
    category: 'photography',
    description: 'Scenic natural beauty',
    promptPrefix: 'Epic landscape photography, Peter Lik and Marc Adamus inspired, vibrant saturated colors, dramatic sky with volumetric clouds, foreground interest leading to distant peaks, hyperfocal distance sharpness throughout, polarized deep blue sky, golden hour warmth, National Geographic cover quality, grand sense of scale and wonder',
  },
  {
    id: 'long-exposure',
    name: 'Long Exposure',
    category: 'photography',
    description: 'Motion blur, light trails',
    promptPrefix: 'Stunning long exposure photography, silky smooth water like glass, star trails or light painting, ghostly motion blur, ND filter effect, tripod-sharp stationary elements, ethereal dreamlike quality, 30 second exposure aesthetic',
  },
  {
    id: 'infrared',
    name: 'Infrared',
    category: 'photography',
    description: 'Surreal false colors',
    promptPrefix: 'Otherworldly infrared photography, snow-white foliage glowing against deep burgundy sky, surreal false color palette, dreamlike alien landscape, invisible light spectrum revealed, ethereal and haunting atmosphere',
  },
  {
    id: 'vintage-film',
    name: 'Vintage Film',
    category: 'photography',
    description: 'Analog film grain',
    promptPrefix: 'Authentic vintage film photography, Kodak Portra 400 color science, organic film grain texture, subtle light leaks, slightly lifted blacks, nostalgic warm tones, 35mm film aesthetic, imperfect but beautiful analog character',
  },
  {
    id: 'hdr',
    name: 'HDR',
    category: 'photography',
    description: 'High dynamic range',
    promptPrefix: 'Masterful HDR photography, impossible dynamic range revealing detail in deepest shadows and brightest highlights simultaneously, hyper-real vivid colors, dramatic tone-mapped sky, every texture and detail visible, punchy contrast, professional real estate or architectural photography quality',
  },
  {
    id: 'street-photography',
    name: 'Street Photography',
    category: 'photography',
    description: 'Urban candid moments',
    promptPrefix: 'Compelling street photography, Henri Cartier-Bresson decisive moment, candid urban life, dynamic composition, natural available light, authentic human stories, gritty city atmosphere, documentary aesthetic',
  },
  {
    id: 'astrophotography',
    name: 'Astrophotography',
    category: 'photography',
    description: 'Stars and Milky Way',
    promptPrefix: 'Breathtaking astrophotography, crystal clear Milky Way arc, thousands of stars visible, long exposure night sky, foreground silhouette interest, low light pollution, astronomical precision, cosmic wonder',
  },
  {
    id: 'underwater',
    name: 'Underwater',
    category: 'photography',
    description: 'Ocean and marine life',
    promptPrefix: 'Stunning underwater photography, crystal clear tropical water, vibrant coral reef colors, marine life in natural habitat, light rays penetrating surface, professional dive photography, National Geographic ocean quality',
  },
  {
    id: 'architecture',
    name: 'Architecture',
    category: 'photography',
    description: 'Buildings and structure',
    promptPrefix: 'Professional architecture photography, perfect vertical lines, stunning modern or classical buildings, dramatic sky backdrop, golden hour facade lighting, Iwan Baan and Julius Shulman inspired, structural elegance',
  },
  {
    id: 'wildlife',
    name: 'Wildlife',
    category: 'photography',
    description: 'Animals in nature',
    promptPrefix: 'Award-winning wildlife photography, animal in natural habitat, perfect focus on eyes, beautiful bokeh background, peak action moment, Frans Lanting and Nick Brandt inspired, intimate connection with subject',
  },
  {
    id: 'food-photography',
    name: 'Food Photography',
    category: 'photography',
    description: 'Culinary styling',
    promptPrefix: 'Mouthwatering food photography, professional culinary styling, appetizing colors and textures, elegant plating on rustic surface, soft directional window light, shallow depth of field, Bon Appetit magazine quality',
  },
  {
    id: 'fashion',
    name: 'Fashion',
    category: 'photography',
    description: 'Editorial, high fashion',
    promptPrefix: 'High fashion editorial photography, Vogue magazine quality, dramatic model pose, designer clothing details visible, professional studio or exotic location lighting, Mario Testino and Annie Leibovitz inspired',
  },
  {
    id: 'documentary',
    name: 'Documentary',
    category: 'photography',
    description: 'Journalistic storytelling',
    promptPrefix: 'Powerful documentary photography, authentic human story captured, Steve McCurry and Sebastiao Salgado inspired, emotional depth, available light, decisive moment, photojournalism excellence',
  },
  {
    id: 'minimalist-photo',
    name: 'Minimalist Photo',
    category: 'photography',
    description: 'Simple, clean compositions',
    promptPrefix: 'Minimalist photography, vast negative space, single point of interest, clean geometric composition, muted color palette, serene and contemplative, architectural simplicity, Japanese aesthetic influence',
  },
  {
    id: 'high-key',
    name: 'High Key',
    category: 'photography',
    description: 'Bright, luminous whites',
    promptPrefix: 'High key photography, predominantly bright white tones, minimal shadows, ethereal luminous quality, overexposed background, airy and fresh feeling, beauty and product photography style',
  },
  {
    id: 'low-key',
    name: 'Low Key',
    category: 'photography',
    description: 'Dramatic dark shadows',
    promptPrefix: 'Low key photography, predominantly dark tones with selective highlights, chiaroscuro drama, mysterious atmosphere, single light source, Caravaggio-inspired shadows, noir mood',
  },
  {
    id: 'tilt-shift',
    name: 'Tilt-Shift',
    category: 'photography',
    description: 'Miniature effect',
    promptPrefix: 'Tilt-shift photography, selective focus creating miniature diorama effect, aerial city view looking like toy model, saturated colors, fake miniature aesthetic, Lensbaby style blur',
  },
];

export const categories = [
  { id: 'all', name: 'All Styles' },
  { id: 'classic', name: 'Classic Fine Art' },
  { id: 'fine-art', name: 'Modern Fine Art' },
  { id: 'modern', name: 'Modern & Digital' },
  { id: 'photography', name: 'Photography' },
] as const;
