import { ArtStyle } from '@/types';

export const artStyles: ArtStyle[] = [
  // Classic Fine Art
  {
    id: 'impressionism',
    name: 'Impressionism',
    category: 'classic',
    description: 'Soft brushstrokes, light and color',
    promptPrefix: 'Impressionist painting style, soft brushstrokes, vibrant light and color, reminiscent of Monet',
  },
  {
    id: 'post-impressionism',
    name: 'Post-Impressionism',
    category: 'classic',
    description: 'Bold colors, expressive forms',
    promptPrefix: 'Post-Impressionist painting style, bold expressive colors, distinctive brushwork like Van Gogh',
  },
  {
    id: 'baroque',
    name: 'Baroque',
    category: 'classic',
    description: 'Dramatic, rich, ornate',
    promptPrefix: 'Baroque painting style, dramatic lighting, rich colors, ornate details, chiaroscuro',
  },
  {
    id: 'renaissance',
    name: 'Renaissance',
    category: 'classic',
    description: 'Classical beauty, perspective',
    promptPrefix: 'Renaissance painting style, classical beauty, perfect perspective, harmonious composition',
  },
  {
    id: 'art-nouveau',
    name: 'Art Nouveau',
    category: 'classic',
    description: 'Organic lines, decorative',
    promptPrefix: 'Art Nouveau style, flowing organic lines, decorative patterns, elegant curves like Mucha',
  },
  {
    id: 'art-deco',
    name: 'Art Deco',
    category: 'classic',
    description: 'Geometric, glamorous, bold',
    promptPrefix: 'Art Deco style, geometric patterns, bold symmetry, glamorous luxury, gold accents',
  },
  {
    id: 'surrealism',
    name: 'Surrealism',
    category: 'classic',
    description: 'Dreamlike, fantastical',
    promptPrefix: 'Surrealist painting style, dreamlike imagery, fantastical elements like Salvador Dali',
  },
  {
    id: 'romanticism',
    name: 'Romanticism',
    category: 'classic',
    description: 'Emotional, sublime nature',
    promptPrefix: 'Romantic era painting style, emotional intensity, sublime landscapes, dramatic atmosphere',
  },
  {
    id: 'pre-raphaelite',
    name: 'Pre-Raphaelite',
    category: 'classic',
    description: 'Vivid colors, intricate detail',
    promptPrefix: 'Pre-Raphaelite painting style, vivid colors, intricate details, medieval romanticism',
  },
  {
    id: 'ukiyo-e',
    name: 'Ukiyo-e',
    category: 'classic',
    description: 'Japanese woodblock prints',
    promptPrefix: 'Ukiyo-e Japanese woodblock print style, flat colors, bold outlines like Hokusai',
  },
  {
    id: 'pointillism',
    name: 'Pointillism',
    category: 'classic',
    description: 'Dots of pure color',
    promptPrefix: 'Pointillist painting style, composed of small dots of pure color like Seurat',
  },
  {
    id: 'fauvism',
    name: 'Fauvism',
    category: 'classic',
    description: 'Wild, vibrant colors',
    promptPrefix: 'Fauvist painting style, wild vibrant colors, bold brushwork like Matisse',
  },

  // Modern & Digital
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    category: 'modern',
    description: 'Neon, futuristic, dystopian',
    promptPrefix: 'Cyberpunk art style, neon lights, futuristic dystopian, high tech low life aesthetic',
  },
  {
    id: 'vaporwave',
    name: 'Vaporwave',
    category: 'modern',
    description: 'Retro-futuristic, nostalgic',
    promptPrefix: 'Vaporwave aesthetic, pink and cyan colors, retro-futuristic, 80s nostalgia, glitch elements',
  },
  {
    id: 'synthwave',
    name: 'Synthwave',
    category: 'modern',
    description: 'Retro 80s, neon grids',
    promptPrefix: 'Synthwave retro style, neon pink and purple, 80s grid landscapes, chrome reflections',
  },
  {
    id: 'minimalist',
    name: 'Minimalist',
    category: 'modern',
    description: 'Clean, simple, elegant',
    promptPrefix: 'Minimalist art style, clean lines, simple shapes, elegant negative space, refined',
  },
  {
    id: 'abstract-expressionism',
    name: 'Abstract Expressionism',
    category: 'modern',
    description: 'Bold, emotional abstraction',
    promptPrefix: 'Abstract Expressionist painting, bold gestural brushstrokes, emotional intensity',
  },
  {
    id: 'pop-art',
    name: 'Pop Art',
    category: 'modern',
    description: 'Bold colors, commercial art',
    promptPrefix: 'Pop Art style, bold primary colors, Ben-Day dots, commercial aesthetic like Warhol',
  },
  {
    id: 'bauhaus',
    name: 'Bauhaus',
    category: 'modern',
    description: 'Functional, geometric shapes',
    promptPrefix: 'Bauhaus design style, primary colors, geometric shapes, functional modernism',
  },
  {
    id: 'geometric',
    name: 'Geometric Abstract',
    category: 'modern',
    description: 'Pure shapes and forms',
    promptPrefix: 'Geometric abstract art, pure shapes, mathematical precision, bold color blocks',
  },
  {
    id: 'glitch-art',
    name: 'Glitch Art',
    category: 'modern',
    description: 'Digital corruption aesthetic',
    promptPrefix: 'Glitch art style, digital corruption, pixel sorting, chromatic aberration, databending',
  },
  {
    id: 'low-poly',
    name: 'Low Poly',
    category: 'modern',
    description: 'Triangular faceted surfaces',
    promptPrefix: 'Low poly 3D art style, triangular facets, crystalline surfaces, modern digital',
  },
  {
    id: 'pixel-art',
    name: 'Pixel Art',
    category: 'modern',
    description: 'Retro game aesthetic',
    promptPrefix: 'Pixel art style, 16-bit aesthetic, retro gaming, limited color palette',
  },
  {
    id: 'neon-noir',
    name: 'Neon Noir',
    category: 'modern',
    description: 'Dark, moody, neon accents',
    promptPrefix: 'Neon noir style, dark moody atmosphere, neon light accents, cinematic shadows',
  },

  // Modern Fine Art Styles
  {
    id: 'color-field',
    name: 'Color Field',
    category: 'fine-art',
    description: 'Large planes of color, Rothko-inspired',
    promptPrefix: 'Color Field painting in the style of Mark Rothko, luminous rectangular color planes with soft edges, transcendent and meditative, subtle color gradations, spiritual depth through pure color relationships, museum-quality fine art',
  },
  {
    id: 'hard-edge',
    name: 'Hard Edge',
    category: 'fine-art',
    description: 'Sharp geometric boundaries',
    promptPrefix: 'Hard Edge painting style, crisp precise geometric shapes with razor-sharp boundaries, flat unmodulated color areas, bold color contrasts, Ellsworth Kelly and Frank Stella inspired, pristine execution',
  },
  {
    id: 'lyrical-abstraction',
    name: 'Lyrical Abstraction',
    category: 'fine-art',
    description: 'Flowing, expressive forms',
    promptPrefix: 'Lyrical Abstraction painting, flowing organic forms, expressive gestural marks, luminous washes of color, poetic and emotional, Helen Frankenthaler soak-stain technique, ethereal and graceful',
  },
  {
    id: 'neo-expressionism',
    name: 'Neo-Expressionism',
    category: 'fine-art',
    description: 'Raw, intense, Basquiat-style',
    promptPrefix: 'Neo-Expressionist painting, raw emotional intensity, bold primitive marks, graffiti influences, Basquiat and Schnabel inspired, visceral energy, thick impasto textures, symbolic imagery, urban edge',
  },
  {
    id: 'contemporary-realism',
    name: 'Contemporary Realism',
    category: 'fine-art',
    description: 'Photorealistic modern subjects',
    promptPrefix: 'Contemporary Realism painting, photorealistic precision with modern sensibility, hyperreal details, dramatic contemporary lighting, Chuck Close and Richard Estes inspired, technically masterful execution',
  },
  {
    id: 'digital-fine-art',
    name: 'Digital Fine Art',
    category: 'fine-art',
    description: 'High-end digital painting',
    promptPrefix: 'Museum-quality digital fine art, sophisticated digital painting techniques, rich layered textures, contemporary digital masters style, exhibition-worthy digital artwork, refined and polished',
  },
  {
    id: 'mixed-media',
    name: 'Mixed Media',
    category: 'fine-art',
    description: 'Layered textures, collage',
    promptPrefix: 'Mixed media fine art, layered collage textures, torn paper edges, paint drips over photographs, Robert Rauschenberg combines style, rich tactile surfaces, found object aesthetic',
  },
  {
    id: 'conceptual-minimal',
    name: 'Conceptual Minimal',
    category: 'fine-art',
    description: 'Idea-driven, spare aesthetic',
    promptPrefix: 'Conceptual Minimalist art, spare and intentional, Donald Judd and Sol LeWitt inspired, pure form and idea, industrial materials aesthetic, gallery white space, intellectual rigor',
  },
  {
    id: 'new-media',
    name: 'New Media Art',
    category: 'fine-art',
    description: 'Technology-inspired aesthetics',
    promptPrefix: 'New Media digital art, technology-inspired contemporary aesthetics, data visualization beauty, generative art patterns, TeamLab and Refik Anadol inspired, immersive digital experience',
  },
  {
    id: 'process-art',
    name: 'Process Art',
    category: 'fine-art',
    description: 'Evidence of creation visible',
    promptPrefix: 'Process Art style, visible evidence of artistic creation, drips and splatters, Pollock action painting energy, spontaneous mark-making, raw creative process captured, authentic and unpolished',
  },

  // Photography Styles
  {
    id: 'cinematic',
    name: 'Cinematic',
    category: 'photography',
    description: 'Movie-like, dramatic',
    promptPrefix: 'Award-winning cinematic photography, ARRI Alexa camera aesthetic, anamorphic lens flares, film grain texture, Hollywood color grading with teal shadows and orange highlights, dramatic volumetric lighting with god rays, shallow depth of field f/1.4, professional movie still quality, Roger Deakins inspired cinematography',
  },
  {
    id: 'film-noir',
    name: 'Film Noir',
    category: 'photography',
    description: 'High contrast, shadows',
    promptPrefix: 'Classic film noir photography, stark black and white with deep shadows, venetian blind light patterns, cigarette smoke wisps, wet rain-slicked streets reflecting neon, high contrast chiaroscuro lighting, 1940s detective movie aesthetic, moody and mysterious atmosphere',
  },
  {
    id: 'golden-hour',
    name: 'Golden Hour',
    category: 'photography',
    description: 'Warm sunset lighting',
    promptPrefix: 'Breathtaking golden hour photography, warm amber and honey tones, long dramatic shadows, sun flare and lens bloom, backlit subjects with rim lighting, soft diffused sunlight, magical warm atmosphere, professional landscape photography, 85mm lens portrait quality',
  },
  {
    id: 'blue-hour',
    name: 'Blue Hour',
    category: 'photography',
    description: 'Cool twilight tones',
    promptPrefix: 'Ethereal blue hour photography, deep cobalt and indigo twilight sky, city lights beginning to glow, long exposure smoothness, reflections on water, serene melancholic mood, professional twilight landscape, cool color temperature 4000K',
  },
  {
    id: 'macro',
    name: 'Macro Photography',
    category: 'photography',
    description: 'Extreme close-up detail',
    promptPrefix: 'Stunning macro photography, extreme close-up revealing hidden worlds, razor-thin depth of field, water droplets as lenses, intricate textures and patterns, professional focus stacking sharpness, vibrant colors, nature documentary quality, 100mm macro lens',
  },
  {
    id: 'aerial',
    name: 'Aerial View',
    category: 'photography',
    description: 'Bird\'s eye perspective',
    promptPrefix: 'Dramatic aerial photography, stunning birds eye perspective revealing patterns and scale, abstract geometric compositions from above, professional drone cinematography, rich saturated colors, epic sense of scale, National Geographic quality',
  },
  {
    id: 'portrait',
    name: 'Portrait',
    category: 'photography',
    description: 'Elegant portrait lighting',
    promptPrefix: 'Museum-quality portrait photography, Rembrandt lighting with perfect catchlights, creamy bokeh background f/1.2, skin texture visible but flattering, 85mm lens compression, studio quality three-point lighting, emotional depth in eyes, Annie Leibovitz inspired portraiture',
  },
  {
    id: 'landscape',
    name: 'Landscape',
    category: 'photography',
    description: 'Scenic natural beauty',
    promptPrefix: 'Epic landscape photography, Ansel Adams inspired composition, dramatic sky with volumetric clouds, foreground interest leading to distant peaks, hyperfocal distance sharpness throughout, polarized deep blue sky, National Geographic cover quality, grand sense of scale and wonder',
  },
  {
    id: 'long-exposure',
    name: 'Long Exposure',
    category: 'photography',
    description: 'Motion blur, light trails',
    promptPrefix: 'Stunning long exposure photography, silky smooth water like glass, star trails or light painting, ghostly motion blur, ND filter effect, tripod-sharp stationary elements, ethereal dreamlike quality, 30 second exposure aesthetic',
  },
  {
    id: 'infrared',
    name: 'Infrared',
    category: 'photography',
    description: 'Surreal false colors',
    promptPrefix: 'Otherworldly infrared photography, snow-white foliage glowing against deep burgundy sky, surreal false color palette, dreamlike alien landscape, invisible light spectrum revealed, ethereal and haunting atmosphere',
  },
  {
    id: 'vintage-film',
    name: 'Vintage Film',
    category: 'photography',
    description: 'Analog film grain',
    promptPrefix: 'Authentic vintage film photography, Kodak Portra 400 color science, organic film grain texture, subtle light leaks, slightly lifted blacks, nostalgic warm tones, 35mm film aesthetic, imperfect but beautiful analog character',
  },
  {
    id: 'hdr',
    name: 'HDR',
    category: 'photography',
    description: 'High dynamic range',
    promptPrefix: 'Masterful HDR photography, impossible dynamic range revealing detail in deepest shadows and brightest highlights simultaneously, hyper-real vivid colors, dramatic tone-mapped sky, every texture and detail visible, punchy contrast, professional real estate or architectural photography quality',
  },
];

export const categories = [
  { id: 'all', name: 'All Styles' },
  { id: 'classic', name: 'Classic Fine Art' },
  { id: 'fine-art', name: 'Modern Fine Art' },
  { id: 'modern', name: 'Modern & Digital' },
  { id: 'photography', name: 'Photography' },
] as const;
