import { ArtStyle } from '@/types';

export const artStyles: ArtStyle[] = [
  // Classic Fine Art
  {
    id: 'impressionism',
    name: 'Impressionism',
    category: 'classic',
    description: 'Soft brushstrokes, light and color',
    promptPrefix: 'Impressionist painting style, soft brushstrokes, vibrant light and color, reminiscent of Monet',
  },
  {
    id: 'post-impressionism',
    name: 'Post-Impressionism',
    category: 'classic',
    description: 'Bold colors, expressive forms',
    promptPrefix: 'Post-Impressionist painting style, bold expressive colors, distinctive brushwork like Van Gogh',
  },
  {
    id: 'baroque',
    name: 'Baroque',
    category: 'classic',
    description: 'Dramatic, rich, ornate',
    promptPrefix: 'Baroque painting style, dramatic lighting, rich colors, ornate details, chiaroscuro',
  },
  {
    id: 'renaissance',
    name: 'Renaissance',
    category: 'classic',
    description: 'Classical beauty, perspective',
    promptPrefix: 'Renaissance painting style, classical beauty, perfect perspective, harmonious composition',
  },
  {
    id: 'art-nouveau',
    name: 'Art Nouveau',
    category: 'classic',
    description: 'Organic lines, decorative',
    promptPrefix: 'Art Nouveau style, flowing organic lines, decorative patterns, elegant curves like Mucha',
  },
  {
    id: 'art-deco',
    name: 'Art Deco',
    category: 'classic',
    description: 'Geometric, glamorous, bold',
    promptPrefix: 'Art Deco style, geometric patterns, bold symmetry, glamorous luxury, gold accents',
  },
  {
    id: 'surrealism',
    name: 'Surrealism',
    category: 'classic',
    description: 'Dreamlike, fantastical',
    promptPrefix: 'Surrealist painting style, dreamlike imagery, fantastical elements like Salvador Dali',
  },
  {
    id: 'romanticism',
    name: 'Romanticism',
    category: 'classic',
    description: 'Emotional, sublime nature',
    promptPrefix: 'Romantic era painting style, emotional intensity, sublime landscapes, dramatic atmosphere',
  },
  {
    id: 'pre-raphaelite',
    name: 'Pre-Raphaelite',
    category: 'classic',
    description: 'Vivid colors, intricate detail',
    promptPrefix: 'Pre-Raphaelite painting style, vivid colors, intricate details, medieval romanticism',
  },
  {
    id: 'ukiyo-e',
    name: 'Ukiyo-e',
    category: 'classic',
    description: 'Japanese woodblock prints',
    promptPrefix: 'Ukiyo-e Japanese woodblock print style, flat colors, bold outlines like Hokusai',
  },
  {
    id: 'pointillism',
    name: 'Pointillism',
    category: 'classic',
    description: 'Dots of pure color',
    promptPrefix: 'Pointillist painting style, composed of small dots of pure color like Seurat',
  },
  {
    id: 'fauvism',
    name: 'Fauvism',
    category: 'classic',
    description: 'Wild, vibrant colors',
    promptPrefix: 'Fauvist painting style, wild vibrant colors, bold brushwork like Matisse',
  },

  // Modern & Digital
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    category: 'modern',
    description: 'Neon, futuristic, dystopian',
    promptPrefix: 'Cyberpunk art style, neon lights, futuristic dystopian, high tech low life aesthetic',
  },
  {
    id: 'vaporwave',
    name: 'Vaporwave',
    category: 'modern',
    description: 'Retro-futuristic, nostalgic',
    promptPrefix: 'Vaporwave aesthetic, pink and cyan colors, retro-futuristic, 80s nostalgia, glitch elements',
  },
  {
    id: 'synthwave',
    name: 'Synthwave',
    category: 'modern',
    description: 'Retro 80s, neon grids',
    promptPrefix: 'Synthwave retro style, neon pink and purple, 80s grid landscapes, chrome reflections',
  },
  {
    id: 'minimalist',
    name: 'Minimalist',
    category: 'modern',
    description: 'Clean, simple, elegant',
    promptPrefix: 'Minimalist art style, clean lines, simple shapes, elegant negative space, refined',
  },
  {
    id: 'abstract-expressionism',
    name: 'Abstract Expressionism',
    category: 'modern',
    description: 'Bold, emotional abstraction',
    promptPrefix: 'Abstract Expressionist painting, bold gestural brushstrokes, emotional intensity',
  },
  {
    id: 'pop-art',
    name: 'Pop Art',
    category: 'modern',
    description: 'Bold colors, commercial art',
    promptPrefix: 'Pop Art style, bold primary colors, Ben-Day dots, commercial aesthetic like Warhol',
  },
  {
    id: 'bauhaus',
    name: 'Bauhaus',
    category: 'modern',
    description: 'Functional, geometric shapes',
    promptPrefix: 'Bauhaus design style, primary colors, geometric shapes, functional modernism',
  },
  {
    id: 'geometric',
    name: 'Geometric Abstract',
    category: 'modern',
    description: 'Pure shapes and forms',
    promptPrefix: 'Geometric abstract art, pure shapes, mathematical precision, bold color blocks',
  },
  {
    id: 'glitch-art',
    name: 'Glitch Art',
    category: 'modern',
    description: 'Digital corruption aesthetic',
    promptPrefix: 'Glitch art style, digital corruption, pixel sorting, chromatic aberration, databending',
  },
  {
    id: 'low-poly',
    name: 'Low Poly',
    category: 'modern',
    description: 'Triangular faceted surfaces',
    promptPrefix: 'Low poly 3D art style, triangular facets, crystalline surfaces, modern digital',
  },
  {
    id: 'pixel-art',
    name: 'Pixel Art',
    category: 'modern',
    description: 'Retro game aesthetic',
    promptPrefix: 'Pixel art style, 16-bit aesthetic, retro gaming, limited color palette',
  },
  {
    id: 'neon-noir',
    name: 'Neon Noir',
    category: 'modern',
    description: 'Dark, moody, neon accents',
    promptPrefix: 'Neon noir style, dark moody atmosphere, neon light accents, cinematic shadows',
  },

  // Photography Styles
  {
    id: 'cinematic',
    name: 'Cinematic',
    category: 'photography',
    description: 'Movie-like, dramatic',
    promptPrefix: 'Cinematic photography style, dramatic lighting, wide aspect ratio, movie still aesthetic',
  },
  {
    id: 'film-noir',
    name: 'Film Noir',
    category: 'photography',
    description: 'High contrast, shadows',
    promptPrefix: 'Film noir photography style, high contrast black and white, dramatic shadows, moody',
  },
  {
    id: 'golden-hour',
    name: 'Golden Hour',
    category: 'photography',
    description: 'Warm sunset lighting',
    promptPrefix: 'Golden hour photography, warm sunset light, soft shadows, magical atmosphere',
  },
  {
    id: 'blue-hour',
    name: 'Blue Hour',
    category: 'photography',
    description: 'Cool twilight tones',
    promptPrefix: 'Blue hour photography, twilight atmosphere, cool blue tones, serene mood',
  },
  {
    id: 'macro',
    name: 'Macro Photography',
    category: 'photography',
    description: 'Extreme close-up detail',
    promptPrefix: 'Macro photography style, extreme close-up, incredible detail, shallow depth of field',
  },
  {
    id: 'aerial',
    name: 'Aerial View',
    category: 'photography',
    description: 'Bird\'s eye perspective',
    promptPrefix: 'Aerial photography, bird\'s eye view, dramatic perspective, landscape from above',
  },
  {
    id: 'portrait',
    name: 'Portrait',
    category: 'photography',
    description: 'Elegant portrait lighting',
    promptPrefix: 'Professional portrait photography, elegant lighting, beautiful composition',
  },
  {
    id: 'landscape',
    name: 'Landscape',
    category: 'photography',
    description: 'Scenic natural beauty',
    promptPrefix: 'Landscape photography, scenic natural beauty, epic composition, stunning vistas',
  },
  {
    id: 'long-exposure',
    name: 'Long Exposure',
    category: 'photography',
    description: 'Motion blur, light trails',
    promptPrefix: 'Long exposure photography, motion blur, light trails, smooth water, ethereal',
  },
  {
    id: 'infrared',
    name: 'Infrared',
    category: 'photography',
    description: 'Surreal false colors',
    promptPrefix: 'Infrared photography style, surreal colors, white foliage, dreamlike atmosphere',
  },
  {
    id: 'vintage-film',
    name: 'Vintage Film',
    category: 'photography',
    description: 'Analog film grain',
    promptPrefix: 'Vintage film photography, analog grain, nostalgic colors, 35mm aesthetic',
  },
  {
    id: 'hdr',
    name: 'HDR',
    category: 'photography',
    description: 'High dynamic range',
    promptPrefix: 'HDR photography, high dynamic range, vivid colors, enhanced detail in shadows and highlights',
  },
];

export const categories = [
  { id: 'all', name: 'All Styles' },
  { id: 'classic', name: 'Classic Fine Art' },
  { id: 'modern', name: 'Modern & Digital' },
  { id: 'photography', name: 'Photography' },
] as const;
